services:
  - type: web
    name: tutorialWebsite
    runtime: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
